// Generate PDF Statement
// Creates PDF using jsPDF

import { NextRequest, NextResponse } from 'next/server'
import jsPDF from 'jspdf'

export async function POST(request: NextRequest) {
  try {
    const data = await request.json()

    // Create PDF
    const doc = new jsPDF()

    // Header
    doc.setFontSize(24)
    doc.setTextColor(79, 70, 229) // Indigo
    doc.text('Consignments.ai', 20, 20)

    doc.setFontSize(18)
    doc.setTextColor(0, 0, 0)
    doc.text('Owner Statement', 20, 35)

    // Owner Info
    doc.setFontSize(12)
    doc.text(`Owner: ${data.owner.business_name}`, 20, 50)
    doc.text(`Period: ${data.period.start} to ${data.period.end}`, 20, 58)
    doc.text(`Statement Date: ${new Date().toLocaleDateString()}`, 20, 66)

    // Divider
    doc.setLineWidth(0.5)
    doc.line(20, 72, 190, 72)

    // Revenue Section
    let y = 85
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Revenue Summary', 20, y)

    y += 10
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')

    doc.text('Gross Rental Income', 20, y)
    doc.text(`$${Number(data.gross_income).toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y, { align: 'right' })

    y += 8
    doc.text('Platform Fee (10%)', 30, y)
    doc.text(`-$${Number(data.platform_fees).toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y, { align: 'right' })

    y += 8
    doc.text('Cleaning Fees', 30, y)
    doc.text(`-$${Number(data.cleaning_fees).toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y, { align: 'right' })

    y += 8
    doc.text('Expenses', 30, y)
    doc.text(`-$${Number(data.expenses).toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y, { align: 'right' })

    y += 10
    doc.setLineWidth(0.3)
    doc.line(20, y, 190, y)

    y += 8
    doc.setFont('helvetica', 'bold')
    doc.text('Net Income', 20, y)
    doc.text(`$${Number(data.net_income).toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y, { align: 'right' })

    y += 10
    doc.setFont('helvetica', 'normal')
    doc.text(`Your Split (${data.owner.revenue_split_percentage}%)`, 30, y)
    doc.text(`× ${data.owner.revenue_split_percentage}%`, 190, y, { align: 'right' })

    y += 12
    doc.setLineWidth(1)
    doc.line(20, y, 190, y)

    y += 10
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(79, 70, 229)
    doc.text('YOUR PAYOUT', 20, y)
    doc.text(`$${Number(data.owner_payout).toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 190, y, { align: 'right' })

    // Bookings Detail
    if (data.bookings && data.bookings.length > 0) {
      y += 15
      doc.setFontSize(14)
      doc.setTextColor(0, 0, 0)
      doc.text('Bookings Detail', 20, y)

      y += 8
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.text('Booking #', 20, y)
      doc.text('RV', 60, y)
      doc.text('Dates', 110, y)
      doc.text('Amount', 190, y, { align: 'right' })

      y += 6
      doc.setFont('helvetica', 'normal')

      data.bookings.slice(0, 10).forEach((booking: any) => {
        if (y > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(booking.booking_number, 20, y)
        doc.text(booking.asset_name || 'N/A', 60, y)
        doc.text(`${booking.start_date} - ${booking.end_date}`, 110, y)
        doc.text(`$${Number(booking.amount).toFixed(2)}`, 190, y, { align: 'right' })
        y += 6
      })
    }

    // Expenses Detail
    if (data.expense_items && data.expense_items.length > 0) {
      y += 10
      if (y > 250) {
        doc.addPage()
        y = 20
      }

      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.text('Expenses Detail', 20, y)

      y += 8
      doc.setFontSize(9)
      doc.text('Description', 20, y)
      doc.text('Category', 100, y)
      doc.text('Date', 140, y)
      doc.text('Amount', 190, y, { align: 'right' })

      y += 6
      doc.setFont('helvetica', 'normal')

      data.expense_items.slice(0, 15).forEach((expense: any) => {
        if (y > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(expense.description.substring(0, 40), 20, y)
        doc.text(expense.category, 100, y)
        doc.text(expense.date, 140, y)
        doc.text(`-$${Number(expense.amount).toFixed(2)}`, 190, y, { align: 'right' })
        y += 6
      })
    }

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.text(
        `Page ${i} of ${pageCount} • Generated by Consignments.ai • ${new Date().toLocaleDateString()}`,
        105,
        290,
        { align: 'center' }
      )
    }

    // Generate PDF as buffer
    const pdfBuffer = doc.output('arraybuffer')

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="statement-${owner.business_name}-${period_start}.pdf"`,
      },
    })
  } catch (error) {
    console.error('PDF generation error:', error)
    return NextResponse.json({ error: 'PDF generation failed' }, { status: 500 })
  }
}
